run:
  timeout: 5m
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  goconst:
    min-len: 2
    min-occurrences: 2

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

  gocyclo:
    min-complexity: 15

  goimports:
    local-prefixes: github.com/xeniasokk/field-switcher

  golint:
    min-confidence: 0

  govet:
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - errorsas
      - ifaceassert
      - nilfunc
      - printf
      - stringintconv
      - structtag
      - testinggoroutine
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult

  lll:
    line-length: 120

  maligned:
    suggest-new: true

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  noctx:
    check-exported: false

  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

  revive:
    min-confidence: 0
    rules:
      - name: exported
        severity: warning
      - name: unexported-return
        severity: warning

  staticcheck:
    checks: ["all"]

  stylecheck:
    checks: ["all"]

  unconvert:
    suggestions: true

  unparam:
    check-exported: false

  whitespace:
    multi-if: false
    multi-func: false

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-dirs:
    - vendor
    - bin
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - goconst
        - gocyclo
        - gosec
        - lll
        - noctx
        - unparam
    - linters:
        - revive
      text: "exported.*should have comment"
    - linters:
        - stylecheck
      text: "ST1000.*package comment"
    - linters:
        - gocritic
      text: "hugeParam"

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

